version: "3"
services:
  flask-app:
    build: .
    ports:
      - 10000:5000
    environment:
      - MONGO_DBNAME=devdemonsdb
      - MONGO_URI=mongodb://mdbdevdemons:dd12345@mongodb:27017
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=5000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mdbdevdemons
      - MONGO_INITDB_ROOT_PASSWORD=dd12345
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: